
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "rules_pycross_example"
version = "0.1"
description = "rules_pycross"
authors = []

[tool.poetry.dependencies]
python = "~=3.7"
wheel = "^0.37.1"
ipython = ">=7.34.0"
numpy = ">=1.21.0"

cognitojwt = "*"
setproctitle = "=1.2.2"
tree-sitter = "=0.20.0"
future = "=0.18.2"
opencv-python = ">=4.0"
keyring = "=23.9.1"

moto = {version = "=3.1.1", extras = ["server", "all"]}
SQLAlchemy-Utils = "=0.38.2"
